AWSTemplateFormatVersion: 2010-09-09
Description: Deploy test environment resources for locker
Resources:
  TestUser:
    Type: 'AWS::IAM::User'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b15904b7-3757-4492-b0fc-7e68c9c02af9
  TestGroup:
    Type: 'AWS::IAM::Group'
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonCognitoPowerUser'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 3ad35e6b-c713-488c-b49a-67b8e367dff1
  AddTestUsersToTestGroup:
    Type: 'AWS::IAM::UserToGroupAddition'
    Properties:
      GroupName: !Ref TestGroup
      Users:
        - !Ref TestUser
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0e6ee7fb-5d34-42ba-b929-dd8ca4105884
  SecretsManagerReaderPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: TestSecretsManagerReaderPolicy
      PolicyDocument:
        Statement:
          Effect: Allow
          Action:
            - 'secretsmanager:GetResourcePolicy'
            - 'secretsmanager:GetSecretValue'
            - 'secretsmanager:DescribeSecret'
            - 'secretsmanager:ListSecretVersionIds'
          Resource: !Ref TestSecretManager
      Groups:
        - !Ref TestGroup
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 66f200ab-f116-49a2-aba6-cd06148fec1d
  TestStorageIAMPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: TestStorageIAMPolicy
      PolicyDocument:
        Statement:
          Effect: Allow
          Action:
            - 's3:PutObject'
            - 's3:GetObject'
            - 's3:DeleteObject'
            - 's3:PutObjectAcl'
          Resource: !Join 
            - ''
            - - !GetAtt 
                - TestStorage
                - Arn
              - /*
      Groups:
        - !Ref TestGroup
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 66f200ab-f116-49a2-aba6-cd06148fec1d
  TestStorage:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: environment
          Value: test
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 3c617f1b-429a-4074-ad23-e78b584f5585
    DeletionPolicy: Delete
  TestStoragePolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: TestStorageBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: Test storage permissions
            Effect: Allow
            Principal:
              AWS: !GetAtt 
                - TestUser
                - Arn
            Action:
              - 's3:GetBucketLocation'
              - 's3:ListBucket'
            Resource: !GetAtt 
              - TestStorage
              - Arn
          - Effect: Allow
            Principal:
              AWS: !GetAtt 
                - TestUser
                - Arn
            Action:
              - 's3:PutObject'
              - 's3:GetObject'
              - 's3:DeleteObject'
              - 's3:PutObjectAcl'
            Resource: !Join 
              - ''
              - - !GetAtt 
                  - TestStorage
                  - Arn
                - /*
      Bucket: !Ref TestStorage
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 07c3cf50-8d6c-4e05-8671-84bf9bfca5b9
  TestUserAccessKeys:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref TestUser
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 12229436-db3b-48ad-865e-b13fda2a3cf7
  TestUserPool:
    Type: 'AWS::Cognito::UserPool'
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1 
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AliasAttributes:
        - email
        - preferred_username
        - phone_number
      LambdaConfig:
        PreSignUp: 'arn:aws:lambda:us-east-1:047429572273:function:lambda-trigger-pre-sign-up-auto-confirm-and-verify'
      MfaConfiguration: 'OFF'
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          TemporaryPasswordValidityDays: 1
      Schema:
        - Name: email
          Required: true
          Mutable: true
      UsernameConfiguration:
        CaseSensitive: true
      UserPoolAddOns:
        AdvancedSecurityMode: 'OFF'
      UserPoolName: 'Test-User-Pool'
  TestUserPoolAppClient:
    Type: 'AWS::Cognito::UserPoolClient'
    Properties:
      UserPoolId: !Ref TestUserPool
      ClientName: Test-User-Pool-Client
      GenerateSecret: false
      PreventUserExistenceErrors: 'ENABLED'
  PreSignUpUserPoolPermission:
    Type: AWS::Lambda::Permission
    DependsOn: TestUserPool
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: 'arn:aws:lambda:us-east-1:047429572273:function:lambda-trigger-pre-sign-up-auto-confirm-and-verify'
      Principal: cognito-idp.amazonaws.com
      SourceArn: !GetAtt
        - TestUserPool
        - Arn
  TestEmployeePool:
    Type: 'AWS::Cognito::UserPool'
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1 
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AliasAttributes:
        - email
      LambdaConfig:
        PreSignUp: 'arn:aws:lambda:us-east-1:047429572273:function:lambda-trigger-pre-sign-up-auto-confirm-and-verify'
      MfaConfiguration: 'OFF'
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          TemporaryPasswordValidityDays: 1
      Schema:
        - Name: email
          Required: true
          Mutable: true
      UsernameConfiguration:
        CaseSensitive: true
      UserPoolAddOns:
        AdvancedSecurityMode: 'OFF'
      UserPoolName: 'Test-Employee-Pool'
  TestEmployeePoolAppClient:
    Type: 'AWS::Cognito::UserPoolClient'
    Properties:
      UserPoolId: !Ref TestEmployeePool
      ClientName: Test-Employee-Pool-Client
      GenerateSecret: false
      PreventUserExistenceErrors: 'ENABLED'
  PreSignUpEmployeePoolPermission:
    Type: AWS::Lambda::Permission
    DependsOn: TestEmployeePool
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: 'arn:aws:lambda:us-east-1:047429572273:function:lambda-trigger-pre-sign-up-auto-confirm-and-verify'
      Principal: cognito-idp.amazonaws.com
      SourceArn: !GetAtt
        - TestEmployeePool
        - Arn
  TestSecretManager:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: TestEnvSecretManager
      Description: "Secret manager for all non-resource related secrets for test environment"
      GenerateSecretString:
        SecretStringTemplate: '{"admin_email": "matthew.p.burruss@vanderbit.edu"}'
        GenerateStringKey: "admin_password"
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
Outputs:
  Region:
    Description: The AWS Region
    Value: !Ref 'AWS::Region'
  TestUserAccessKey:
    Value: !Ref TestUserAccessKeys
    Description: AWSAccessKeyId of new user
  TestUserSecretKey:
    Value: !GetAtt 
      - TestUserAccessKeys
      - SecretAccessKey
    Description: AWSSecretAccessKey of new user
  TestBucketName:
    Value: !Ref TestStorage
    Description: The name of the test env storage bucket
  TestUserPoolID:
    Value: !Ref TestUserPool
    Description: The test env User user pool ID
  TestUserPoolClientID:
    Value: !Ref TestUserPoolAppClient
    Description: The client ID for the test env User user pool
  TestEmployeePoolID:
    Value: !Ref TestEmployeePool
    Description: The test env Employee user pool ID
  TestEmployeePoolClientID:
    Value: !Ref TestEmployeePoolAppClient
    Description: The client ID for the test env Employee user pool
  TestSecretManagerARN:
    Value: !Ref TestSecretManager
    Description: The ARN of the Test Secret Manager
    Export:
      Name: TestSecretManagerARN
Metadata:
  'AWS::CloudFormation::Designer':
    3c617f1b-429a-4074-ad23-e78b584f5585:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
    3ad35e6b-c713-488c-b49a-67b8e367dff1:
      size:
        width: 60
        height: 60
      position:
        x: -40
        'y': 190
      z: 1
      embeds: []
      isassociatedwith:
        - add8b1e5-be78-48f9-b81a-6288569d27c9
        - 66f200ab-f116-49a2-aba6-cd06148fec1d
    66f200ab-f116-49a2-aba6-cd06148fec1d:
      size:
        width: 60
        height: 60
      position:
        x: -40
        'y': 90
      z: 1
      embeds: []
      isassociatedwith:
        - 3ad35e6b-c713-488c-b49a-67b8e367dff1
    b15904b7-3757-4492-b0fc-7e68c9c02af9:
      size:
        width: 60
        height: 60
      position:
        x: 170
        'y': 190
      z: 1
      embeds: []
    12229436-db3b-48ad-865e-b13fda2a3cf7:
      size:
        width: 60
        height: 60
      position:
        x: 290
        'y': 190
      z: 1
      embeds: []
    07c3cf50-8d6c-4e05-8671-84bf9bfca5b9:
      size:
        width: 60
        height: 60
      position:
        x: 170
        'y': 90
      z: 1
      embeds: []
      isassociatedwith:
        - 3c617f1b-429a-4074-ad23-e78b584f5585
    0e6ee7fb-5d34-42ba-b929-dd8ca4105884:
      size:
        width: 60
        height: 60
      position:
        x: 70
        'y': 190
      z: 0
      embeds: []
      isassociatedwith:
        - b15904b7-3757-4492-b0fc-7e68c9c02af9
        - 3ad35e6b-c713-488c-b49a-67b8e367dff1
