define({
  "name": "Locker",
  "version": "0.1.0",
  "description": "API Documentation",
  "sampleUrl": "http://localhost:3000",
  "order": [
    "Auth",
    "User",
    "PostApiUsers",
    "PutApiUsersUserIdPassword",
    "PutApiUsersUserIdFollow",
    "DeleteApiUsersUserIdUnFollow",
    "GetApiUsersUserIdFollow",
    "GetApiUsers",
    "GetApiUsersbyID",
    "PutApiUsersUserId",
    "GetApiUsersUserIdAvatar",
    "PostApiUsersUserIdAvatar",
    "DeleteApiUsersUserIdAvatar",
    "DeleteApiUsersUserId",
    "Post",
    "PostApiPosts",
    "GetPosts",
    "GetApiPostsPostID",
    "PutApiPostsPostID",
    "GetApiPostIdComments",
    "DeleteApiPostsPostID",
    "PostAPIPostsPostIdReaction",
    "DeleteAPIPostsPostIdReaction",
    "GetAPIPostsPostIdReaction",
    "Comment",
    "PostApiPostIdComments",
    "GetApiCommentsCommentID",
    "PutApiCommentIdLikes",
    "DeleteApiCommentIdLikes",
    "GetApiCommentIdReplies",
    "DeleteApiCommentsCommentID",
    "Reply",
    "PostApiCommentIdReplies",
    "PutApiCommentIdRepliesReplyIdLikes",
    "DeleteApiCommentIdRepliesReplyIdLikes",
    "GetApiCommentIdRepliesReplyId",
    "PutApiCommentIdRepliesReplyId",
    "DeleteApiCommentIdRepliesReplyId",
    "Miscellaneous",
    "GetMediaKey"
  ],
  "defaultVersion": "0.0.0",
  "apidoc": "0.3.0",
  "generator": {
    "name": "apidoc",
    "time": "2020-08-30T17:19:52.546Z",
    "url": "https://apidocjs.com",
    "version": "0.25.0"
  }
});
